version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:${PORT}'
    environment:
      - PORT=${PORT}
    command: sh -c "npm run start:prod"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
