version: '3.8'
services:
  nest-app:
    build:
      context: .
    ports:
      - '4001:3000'
    environment:
      - PORT=3000
    command: ['npm','run','start:prod']
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=12092004
    ports:
      - '5433:5432'
